name: Test Java Container Action

on: 
  workflow_dispatch:

jobs:
  run-java-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run custom Java action
        uses: ./
        with:
          name: "GitHub"
